### ISSUE TITLE
False kernel count

### ISSUE THREAD

**Issue by BHaugGZPK** [trife/1KK#2]
- if kernels get recognized (see other issue) they are **not counted correctly**
- counted numbers are allways much to high (e.g. 20 kernels = count 400-500)
- they all appear correctly in the "raw data" file, also statistics (mean, stdev, cv) are calculated correctly in the summary file but count is not correct

**Comment by trife** [comment]
The counting code is known to be buggy and currently only serves as an estimate (sometimes poorly). We're working on implementing a better algorithm.

**Comment by RayganahR** [comment]
I still experience the incorrect counting of the kernels. Is there still no better algorithm for the counting of kernels yet? 
And does the kernel count influence the length and width average because if the wrong count is analysed and that is used to calculate the average results for length and width, the average for the length and width would then be incorrect?

**Comment by trife** [comment]
The counting algorithm has not been updated yet but should be soon. The update will be coupled with a different workflow for collecting data which we think will be more robust. The counting process is independent of the measuring process.

**Comment by RayganahR** [comment]
Thank you for your reply... Will you maybe be able to give me an estimated time to when it would most likely be updated to the new algorithm?

**Comment by trife** [comment]
I'm hoping in the next couple months but I can't give a definitive ETA.

**Comment by trife** [comment]
Please evaluate the new version which has an improved workflow, major technical updates, and new algorithm.
